version: '3.8'

services:
  db:
    image: bitnami/mysql:8.4
    container_name: laravel_db
    restart: unless-stopped
    environment:
      # NOTA: Cambia estas credenciales en producción. Puedes moverlas a un archivo .env.docker
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-laravel}
      - MYSQL_USER=${MYSQL_USER:-laravel}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-laravel}
      # Descomentar si quieres permitir contraseña vacía en desarrollo
      # - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - db_data:/bitnami/mysql
    networks:
      - laravel_net

  laravel:
    image: bitnami/laravel:10
    container_name: laravel_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
      - DB_DATABASE=laravel
      # Opcional: APP_ENV=local APP_DEBUG=true APP_URL=http://localhost:8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - laravel_vendor:/app/vendor
    command: ["bash", "-c", "chmod +x docker/start.sh || true; dos2unix docker/start.sh 2>/dev/null || true; ./docker/start.sh"]
    networks:
      - laravel_net

  # Servicio opcional para administrar DB (descomenta si lo deseas)
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:5
  #   container_name: pma
  #   restart: unless-stopped
  #   environment:
  #     - PMA_HOST=db
  #     - PMA_USER=laravel
  #     - PMA_PASSWORD=laravel
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - db
  #   networks:
  #     - laravel_net

networks:
  laravel_net:
    driver: bridge

volumes:
  db_data:
  laravel_vendor:
